title: Noa's Arc
description: A tech blog where I record the process of self-study - 
             hands-on practice, experiments, and lessons learned 
             while working through programming and cybersecurity. 
             It's meant to be a personal "ark" for a fast-changing era.

author: 
  name: "Noa"
  email: "morenoa.iya.25@gmail.com"
  url: "url: https://noas-arc.github.io/"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

github:
  username: Noas-Arc


show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

#toc: true
#gem "github-pages", group: :jekyll_plugins
