remote_theme: pages-theme/hacker@v0.2.0
gem "github-pages", group: :jekyll_plugins

title: Noa's Arc
description: Tech blog where I record the process of self-study - 
             hands-on practice, experiments, and lessons learned 
             while working through programming and cyber security. 
             It's meant to be a personal "ark" for a fast-changing era.

url: 'https://Noas-Arc.github.io'

github:
  username: Noas-Arc


show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

toc: true
